version: '3.1'

services:
  db:
    image: postgres:15
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
